language: python
python: '3.6'
install: make init
script:
- make test
- make build
- codecov
deploy:
  provider: pypi
  user: __token__
  password:
    secure: ioIaSMfOY/Swp3vsRn1OJOawwto85EL+YcEMcJEF9wvtKZ16s95qLmgo4afNR5osPs1ah4pUt7wNniqNfzqz4swNNrH3aANf15iBbav5zzMsviu9Oh8yhjhCWiDj6d+BR4SeJNSGWdBcs8uMvn7R/k3VkoYwYsyNEu3Z+FYF15B2ikkelAHkXMJ/RJuQxIKZThlhzoug3WTF7kIak+oGz81vu8d5zI5S8viUE/REnqVzpjP4V1t+yVu7FAKOBpkWT1UKqWtJ+7Ts6Rdju8RUGPNYEajgHbpuahZe6GV/1q5rAQKqamCGWPTBQ+RUUjTPBpoRYWTpU18fsuG9bVDGUbmyOYIqqLuDSDV4IG/C21TtwfBewDoj7XUmIGTMeQVa+akheDes6pO9Be0BFKXoYTyrlzcdn7KWqjdIh4bp66s1qSaUzwdIqmHDv5pvQg1AQGIynCDi5dzbuhkEHB37fbcXrn6WxLgVkX0YpnhasnEmtGZjRCsmN1cj9bgaU7VcVnmOA/2zGKWuZLiJnNNUF6zjkKKHogwzKWcNBwSJDN4UMg4HQhP6u3z9cB0zrYce9svHvcH46wt1pr6zu9GAgfjxudL8ZRWxfdIoA2ZsVdFjHiUQUg4DMT4QGUb+F4eKwk7ZrHWilLCE7IZbS7ViVq5ChSGNqF0vEXfBe4B2vcw=
  distributions: sdist bdist_wheel
  on:
    branch: master
