language: python
python: "3.6"

jobs:
    include:
        - stage: "Unit tests"
          install: "make init"
          script: "make test"
        - stage: "Deploy"
          if: branch = master
          script: echo Deploy!

